version: 2
jobs:
  build_dev:
    docker:
      - image: circleci/node:6.11
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_dev
      - test:
          requires:
            - build_dev
          # filters:
          #   branches:
          #     only: master
# deployment:
#   npmjs:
#     branch: master
#     commands:
#       - echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
#       - npm publish
